/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AuthWrapper: typeof import('./src/components/AuthComonent/AuthWrapper.vue')['default']
    AutoComplete: typeof import('./src/components/AddUsers/AutoComplete.vue')['default']
    FriendItem: typeof import('./src/components/Friends/FriendItem.vue')['default']
    FriendList: typeof import('./src/components/Friends/FriendList.vue')['default']
    FriendsTransformButton: typeof import('./src/components/Friends/FriendsTransformButton.vue')['default']
    FriendsView: typeof import('./src/components/Friends/FriendsView.vue')['default']
    LogoutButton: typeof import('./src/components/AuthComonent/LogoutButton.vue')['default']
    OriginalList: typeof import('./src/components/Friends/OriginalList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VkButton: typeof import('./src/components/AuthComonent/VkButton.vue')['default']
    VKPostView: typeof import('./src/components/UserView/VKPostView.vue')['default']
  }
}
